language: node_js

install:
  - npm install


node_js:
  - "8"
  - "node"

script:
  - npm run build
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - node_modules

notifications:
  email: false