language: node_js

os:
  - linux
  - windows

node_js:
  - "8"
  - "node"

install:
  - npm install

services:
  - mongodb

before_script:
  - export MONGODB_URL="mongodb://localhost:27017"
  - export DB_NAME="express-ts"
  - sleep 10

script:
  - npm run build
  - npm run lint
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - node_modules

notifications:
  email: false