name: "Build and test"
jobs:
  - job: unit_tests
    pool:
      vmImage: ubuntu-16.04
    variables:
      MONGODB_URL: "mongodb://localhost:27017/express-ts"
      DB_NAME: "express-ts"
    steps:
    - bash: npm ci
      displayName: "Install dependencies"
    - bash: docker run -d -p 27017:27017 -v ~/data:/data/db mongo
      displayName: "Start MongoDB"
    - bash: npm test
      displayName: "Run unit tests"
  
  - job: lint
    pool:
      vmImage: ubuntu-16.04
    steps:
    - bash: npm install
      displayName: "Install dependencies"
    - bash: npm run lint
      displayName: "Run linter"